//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILoginService")]
public interface ILoginService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetData", ReplyAction="http://tempuri.org/ILoginService/GetDataResponse")]
    string GetData();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/GetData", ReplyAction="http://tempuri.org/ILoginService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILoginServiceChannel : ILoginService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoginServiceClient : System.ServiceModel.ClientBase<ILoginService>, ILoginService
{
    
    public LoginServiceClient()
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData()
    {
        return base.Channel.GetData();
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync()
    {
        return base.Channel.GetDataAsync();
    }
}
